# Generated by Django 5.0.7 on 2024-07-28 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name': 'Opportunity'},
        ),
    ]
