# Generated by Django 5.0.7 on 2024-07-28 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0002_alter_opportunity_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opportunity',
            options={'verbose_name_plural': 'Opportunities'},
        ),
    ]
