# Generated by Django 5.0.7 on 2024-07-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0005_alter_event_address_alter_event_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(default='ekurhuleni', max_length=250),
            preserve_default=False,
        ),
    ]
