# Generated by Django 5.0.7 on 2024-07-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0009_walkinbooking_price_walkinbooking_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='telephone_number',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='time',
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='coe.venue'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venue',
            name='size',
            field=models.IntegerField(),
        ),
    ]
