# Generated by Django 5.0.7 on 2024-07-28 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0011_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
    ]
