# Generated by Django 5.0.7 on 2024-07-28 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0012_remove_calendarevent_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_time',
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='end_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='calendarevent',
            name='start_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default='default=datetime.date.today'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default='default=date.today'),
            preserve_default=False,
        ),
    ]
