# Generated by Django 5.0.7 on 2024-07-28 09:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0013_remove_calendarevent_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calendarevent',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
