# Generated by Django 5.0.7 on 2024-07-28 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coe', '0014_remove_calendarevent_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='contact_number',
            new_name='telephone_number',
        ),
    ]
